# Reusable Gradle build workflow
name: Build Gradle

on:
  workflow_call:
    inputs:
      gradle_args:
        description: 'Gradle command arguments (e.g., "build", "build publishToMavenCentral")'
        required: true
        type: string
      java_distribution:
        description: 'Java distribution to use'
        required: false
        type: string
        default: ''
      java_version:
        description: 'Java version to use'
        required: false
        type: string
        default: ''
      runs_on:
        description: 'Runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'
      env:
        description: 'Environment variables, one per line in KEY=value format'
        required: false
        type: string
        default: ''
    secrets:
      env_secrets:
        description: 'Secret environment variables, one per line in KEY=value format'
        required: false

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6.0.1

      - name: Setup Java
        uses: actions/setup-java@v5.1.0
        with:
          distribution: ${{ inputs.java_distribution || vars.DEFAULT_JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.java_version || vars.DEFAULT_JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Set environment variables
        if: inputs.env != ''
        run: echo "${{ inputs.env }}" >> $GITHUB_ENV

      - name: Set secret environment variables
        if: ${{ secrets.env_secrets != '' }}
        run: echo "${{ secrets.env_secrets }}" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew ${{ inputs.gradle_args }}
