name: Update Code Statistics

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight (UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq cloc

      - name: Count Lines of Code and Update Profile
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
        run: |
          chmod +x ./scripts/count-loc.sh ./scripts/update-stats.sh
          ./scripts/count-loc.sh | ./scripts/update-stats.sh

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add profile/ABOUT.md
          git commit -m "chore: update profile with latest code stats" || echo "No changes to commit"
          git push origin HEAD